blog/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'blog.views.index', name='index'),
    url(r'^(?P<uuid>[0-9a-f]{32})/$', 'blog.views.detail', name='detail'),
    url(r'^(?P<pk>\d+)/$', 'blog.views.detail', name='detail'),
    url(r'^new/$', 'blog.views.new', name='new'),
    url(r'^(?P<pk>\d+)/edit/$', 'blog.views.edit', name='edit'),
    url(r'^(?P<pk>\d+)/comments/new$', 'blog.views.comment_new', name='comment_new'),
    url(r'^(?P<post_pk>\d+)/comments/(?P<pk>\d+)/edit/$', 'blog.views.comment_edit', name='comment_edit'),
    url(r'^(?P<post_pk>\d+)/comments/(?P<pk>\d+)/delete/$', 'blog.views.comment_delete', name='comment_delete'),
    url(r'^(?P<username>\w+)/$', 'blog.views.author_wall', name='author_wall')
]

pystagram/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='blog:index')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^photos/', include('photos.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import Q
from django.db.models.signals import pre_save
from uuid import uuid4
from pystagram.validators import jpeg_validator
from pystagram.image import receiver_with_image_field
from pystagram.file import random_name_with_file_field


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    uuid = models.UUIDField(default=uuid4, editable=False, db_index=True)
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=100, db_index=True)
    content = models.TextField()
    photo = models.ImageField(blank=True, null=True, validators=[jpeg_validator],
                              upload_to=random_name_with_file_field)
    lnglat = models.CharField(max_length=100, blank=True, null=True)
    tags = models.ManyToManyField('Tag', blank=True)
    origin_url = models.URLField(blank=True)
    ip = models.GenericIPAddressField(blank=True, null=True)
    is_public = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', args=[self.uuid.hex])

    @property
    def lat(self):
        if self.lnglat:
            return self.lnglat.split(',')[1]

    @property
    def lng(self):
        if self.lnglat:
            return self.lnglat.split(',')[0]

    @classmethod
    def timeline(cls, from_user):
        following_users = [follow.to_user_id for follow in from_user.following_set.all()]
        return cls.objects.filter(Q(author=from_user) | Q(author__in=following_users))

receiver = receiver_with_image_field('photo', 1024)
pre_save.connect(receiver, sender=Post)

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    post = models.ForeignKey(Post)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Tag(models.Model):
    name = models.CharField(max_length=100, db_index=True)

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from blog.models import Post, Comment
from pystagram.widgets import PointWidget

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('category', 'title', 'content', 'photo', 'lnglat', 'tags', 'origin_url')
        widgets = {
            'lnglat': PointWidget,
        }

    def clean_title(self):
        title = self.cleaned_data.get('title').strip()
        if len(title) < 10:
            msg = 'Input more than 10 letters.'
            raise forms.ValidationError(msg)
        return title

    def clean_content(self):
        content = self.cleaned_data.get('content').strip()
        if len(content) < 10:
            msg = 'Input more than 10 letters.'
            raise forms.ValidationError(msg)
        return content

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

blog/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, resolve_url, get_object_or_404
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from blog.decorators import owner_required
from blog.models import Post, Comment
from blog.forms import PostForm, CommentForm

User = get_user_model()

class PostListView(ListView):
    model = Post
    template_name = 'blog/index.html'
    paginate_by = 8

    def get_queryset(self):
        return Post.timeline(self.request.user)

index = login_required(PostListView.as_view())

class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'

    def get_object(self, *args, **kwargs):
        if 'uuid' in self.kwargs:
            return get_object_or_404(Post, uuid=self.kwargs['uuid'])
        return super(PostDetailView, self).get_object(*args, **kwargs)

detail = PostDetailView.as_view()

class PostCreateView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'form.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.ip = self.request.META['REMOTE_ADDR']
        return super(PostCreateView, self).form_valid(form)

new = login_required(PostCreateView.as_view())

class PostUpdateView(UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'form.html'

    @method_decorator(login_required)
    @method_decorator(owner_required(Post, 'pk'))
    def dispatch(self, request, *args, **kwargs):
        return super(self.__class__, self).dispatch(request, *args, **kwargs)

edit = PostUpdateView.as_view()

class CommentCreateView(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'form.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.post = get_object_or_404(Post, pk=self.kwargs['pk'])
        return super(CommentCreateView, self).form_valid(form)

    def get_success_url(self):
        return resolve_url(self.object.post)

comment_new = login_required(CommentCreateView.as_view())

class CommentUpdateView(UpdateView):
    model = Comment
    form_class = CommentForm
    template_name = 'form.html'

    @method_decorator(login_required)
    @method_decorator(owner_required(Comment, 'pk'))
    def dispatch(self, request, *args, **kwargs):
        return super(self.__class__, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return resolve_url(self.object.post)

comment_edit = CommentUpdateView.as_view()

class CommentDeleteView(DeleteView):
    model = Comment
    template_name = 'blog/comment_delete_confirm.html'

    @method_decorator(login_required)
    @method_decorator(owner_required(Comment, 'pk'))
    def dispatch(self, request, *args, **kwargs):
        return super(self.__class__, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return resolve_url(self.object.post)

comment_delete = CommentDeleteView.as_view()

def author_wall(request, username):
    author = get_object_or_404(User, username=username)
    is_follow = request.user.is_follow(author)
    post_list = Post.objects.filter(author=author)
    return render(request, 'blog/author_wall.html', {
        'author': author,
        'is_follow': is_follow,
        'post_list': post_list,
    })

blog/templates/blog/author_wall.html
{% extends "blog/layout.html" %}
{% load bootstrap3 thumbnail %}

{% block navbar_left %}
    <li><a><span class="label label-info">{{ count }}</span></a></li>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
      <div class="col-xs-10">
            <h1>
                {{ author }}
                {% if user != author %}
                    {% if is_follow %}
                        <a href="{% url "user_unfollow" author.username %}?next={{ request.path }}" title="Unfollow">
                            <small class="glyphicon glyphicon-ok text-success"></small>
                        </a>
                    {% else %}
                        <a href="{% url "user_follow" author.username %}?next={{ request.path }}" title="Follow">
                            <small class="glyphicon glyphicon-plus text-muted"></small>
                        </a>
                    {% endif %}
                {% endif %}
            </h1>
        </div>
    </div>
    <div class="row">
        {% for post in post_list %}
            <div class="col-xs-6 col-sm-4 col-md-3">
                <div class="thumbnail">
                    <a href="{% url "blog:detail" post.pk %}">
                        {% if not post.photo %}
                            <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" width="400" height="400" class="img-rounded" />
                        {% else %}
                            {% thumbnail post.photo "400x400" crop="center" as im %}
                                <img src="{{ im.url }}" width="400" height="400" class="img-rounded" />
                            {% endthumbnail %}
                        {% endif %}
                        <div class="caption">
                            <h5>{{ post.title }}</h5>
                        </div>
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

blog/templates/blog/comment_delete_confirm.html
{% extends "blog/layout.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="alert alert-danger">
                    Are you sure to delete this comment?
                </div>

                <p>{{ comment.content }}</p>

                <input type="submit" value="Delete" class="btn btn-danger" />
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/detail.html
{% extends "blog/layout.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-info">
                <div class="panel-heading">
                    {{ post.title }}
                </div>
                <div class="panel-body">
                    {{ post.content|linebreaks }}
                    {% if post.photo %}
                        <p class="text-center">
                            <img src="{{ post.photo.url }}" />
                        </p>
                    {% endif %}
                    {% if post.lnglat %}
                        <hr/>
                        <p class="text-center">
                            <img src="https://maps.googleapis.com/maps/api/staticmap?center={{ post.lat}},{{ post.lng }}&zoom=13&size=600x300&maptype=roadmap&markers=color:red%7Clabel:C%7C{{ post.lat }},{{ post.lng }}" width="300" height="150" />
                        </p>
                    {% endif %}
                </div>
            </div>
            <ul>
            {% for comment in post.comment_set.all %}
                <li>
                    {{ comment.content }}
                    <a href="{% url 'blog:comment_edit' post.pk comment.pk %}">Edit</a>
                    <a href="{% url 'blog:comment_delete' post.pk comment.pk %}">Delete</a>
                </li>
            {% endfor %}
            </ul>

            <a href="{% url 'blog:index' %}" class="btn btn-default">List</a>
            <a href="{% url 'blog:edit' post.pk %}" class="btn btn-info">Edit</a>
            <a href="{% url 'blog:comment_new' post.pk %}" class="btn btn-success">New Comment</a>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/form.html
{% extends "blog/layout.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <form action="" method="POST">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button class="btn btn-primary">
                        {% bootstrap_icon "heart" %} Submit
                    </button>
                {% endbuttons %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/index.html
{% extends "blog/layout.html" %}
{% load bootstrap3 thumbnail %}

{% block navbar_left %}
    <li><a><span class="label label-info">Visit Count: {{ count }}</span></a></li>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        {% for post in post_list %}
            <div class="col-xs-6 col-sm-4 col-md-3">
                <div class="thumbnail">
                    <a href="{% url 'blog:detail' post.pk %}">
                        {% if not post.photo %}
                            <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" width="400" height="400" class="img-rounded" />
                        {% else %}
                            {% thumbnail post.photo "400x400" crop="center" as im %}
                                <img src="{{ im.url }}" width="400" height="400" class="img-rounded" />
                            {% endthumbnail %}
                        {% endif %}
                        <div class="caption">
                            <h5>{{ post.title }}</h5>
                        </div>
                    </a>
                    <a href="{% url "blog:author_wall" post.author.username %}">by {{ post.author }}</a>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="row">
        <div class="col-xs-12">
            <a href="{% url 'blog:new' %}" class="btn btn-default">New Post</a>
        </div>
    </div>
    <div class="row text-center">
        {% bootstrap_pagination page_obj %}
    </div>
</div>
{% endblock %}

blog/templates/blog/layout.html
{% extends "layout.html" %}